---

- name: Local debug play
  hosts: localhost
  roles:
    - varnish
  vars:
    state: present
    ansible_operator_meta:
      namespace: varnish-operator-ansible-system
      name: varnish-samples
