---

- name: Ensure varnish-vcl configmap {{ state }}
  community.kubernetes.k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'varnish-vcl-configmap.yaml.j2') }}"

- name: Ensure Varnish deployment {{ state }}
  community.kubernetes.k8s:
    state: "{{ state }}"
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ ansible_operator_meta.name }}-varnish"
        namespace: "{{ ansible_operator_meta.namespace }}"
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: varnish
        template:
          metadata:
            labels:
              app: varnish
          spec:
            containers:
            - name: varnish
              command:
              - /usr/sbin/varnishd
              - -a :{{ port }}
              - -a localhost:8443,PROXY
              - -p feature=+http2
              - -f /etc/varnish/default.vcl
              - -s {{ storage_backend }},{{ storage_backend_size }}
              image: "docker.io/varnish:{{ version }}"
              volumeMounts:
              - name: config-volume
                mountPath: /etc/varnish/default.vcl
              ports:
                - containerPort: 6081
            volumes:
            - name: config-volume
              configMap:
                name: varnish-vcl

- name: Ensure Varnish service "{{ state }}"
  community.kubernetes.k8s:
    state: "{{ state }}"
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ ansible_operator_meta.name }}-varnish"
        namespace: "{{ ansible_operator_meta.namespace }}"
      spec:
        type: ClusterIP
        ports:
        - port: 6081
          targetPort: 6081
          protocol: TCP
          name: server-port
        selector:
          app: varnish
