---

- name: Ensure Varnish deployment exists
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ ansible_operator_meta.name }}-varnish"
        namespace: "{{ ansible_operator_meta.namespace }}"
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: varnish
        template:
          metadata:
            labels:
              app: varnish
          spec:
            containers:
            - name: varnish
              image: "docker.io/varnish:{{ version }}"
              ports:
                - containerPort: 6081
