---

apiVersion: cache.example.com/v1
kind: Varnish
metadata:
  name: varnish-sample
  namespace: varnish-operator-ansible-system
spec:
  size: 3
  purging_enabled: true
  banning_enabled: true
  port: 6081
  version: 6.5
  limit_memlock: 85983232
  limit_core: infinity
  limit_nofile: 131072
  storage_backend: malloc
  storage_backend_size: 256m
  global_ttl: 5m
  global_grace: 30m
  backends:
    - name: default
      host: 127.0.0.1
      port: 8080
      max_connections: 800
      first_byte_timeout: 600s
      connect_timeout: 600s
      between_bytes_timeout: 600s
      probe_enabled: true
      probe:
        url: "/"
        timeout: 5s
        interval: 30s
        window: 5
        threshold: 3
      requests:
        - url: "/"
          ttl: 1m
          grace: 10m
          keep: 20m
    - name: default2
      host: 127.0.0.1
      port: 8081
      max_connections: 800
      first_byte_timeout: 600s
      connect_timeout: 600s
      between_bytes_timeout: 600s
      probe_enabled: true
      probe:
        url: "/"
        timeout: 5s
        interval: 30s
        window: 5
        threshold: 3
      requests:
        - url: "/"
